version: '3.3'

volumes:
  fg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - fg_data:/var/lib/postgresql/fg_data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always   
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
      - backend
  nginx:
    build: ./nginx/
    ports:
      - 8000:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend