version: '3.3'

volumes:
  fg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - fg_data:/var/lib/postgresql/fg_data
  backend:
    image: svshatun/foodgram_backend  
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: svshatun/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: svshatun/foodgram_nginx
    ports:
      - 7000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend